# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
target 'RxSwiftLearn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
   pod 'RxSwift',    '~> 4.0'
   pod 'RxCocoa',    '~> 4.0'
  # Pods for RxSwiftLearn

  target 'RxSwiftLearnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftLearnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
